### ISSUE TITLE
👍 

### ISSUE THREAD

**Issue by mpgn** [pgormanDS/hash_spider#1]
Good job ! Do you want to create a PR on cme ?

**Comment by pgormanDS** [comment]
Just submitted one. I also submitted one on the porchetta gitlab version last week.

Was hoping to fix a few remaining items before submission but it does fully work in the current state.

**Comment by mpgn** [comment]
For public contribution, I always merge them on the public repo and also push them on the private repo :)
I will wait a little bit for the PR so you can fix what you want ! ;)

**Comment by pgormanDS** [comment]
Got it. I've actually been struggling with the one item. If you see in the screenshot, cme always reports the initial IP and host set. Been trying to figure out how to update that but I'm struggling. I tried messing around but haven't had much luck. Think I just need to look at logger.py closer and try harder.

**Comment by mpgn** [comment]
In your module add the following lines:

```
context.log.extra["port"] = "888"
context.log.extra["host"] = "another"
context.log.extra["hostname"] = "yea"
```
Example:
![image](https://user-images.githubusercontent.com/5891788/151884734-2d8cf7db-abde-4c31-b833-26cf299f31ea.png)

**Comment by pgormanDS** [comment]
There we go! Thank you! I can't tell you how much time I spent looking through context.log trying to find which attribute to modify.

**Comment by pgormanDS** [comment]
Module is ready to be pulled into the main branch.
